// Curated chamber leadership for source-fed states, transcribed from each chamber's
// OFFICIAL leadership page (2025-2026 session, researched 2026-06-22). Matched to the
// loaded roster by name at apply time (see run.ts). California's leadership is handled
// separately, keyed by district, in ../scrape/positions-guide.ts. Refresh ~once/session.
//
// `chamber`: 'senate' = upper house, 'assembly' = lower house (the "House" in most of
// these states), regardless of its real name. Sources are the official .gov pages noted
// per state below; entries with no roster match are reported (not invented) at apply time.
import type { StateCode } from '@legiapp/shared';

export interface LeadershipPosition {
  chamber: 'assembly' | 'senate';
  role: string;
  name: string; // full name exactly as the official page lists it
}

export const LEADERSHIP_BY_STATE: Partial<Record<StateCode, LeadershipPosition[]>> = {
  // nysenate.gov/senate-leadership + nyassembly.gov/mem/leadership
  NY: [
    { chamber: 'senate', role: 'Temporary President and Majority Leader', name: 'Andrea Stewart-Cousins' },
    { chamber: 'senate', role: 'Deputy Majority Leader', name: 'Michael Gianaris' },
    { chamber: 'senate', role: 'Vice President Pro Tempore', name: 'Toby Ann Stavisky' },
    { chamber: 'senate', role: 'Senior Assistant Majority Leader', name: 'Kevin Parker' },
    { chamber: 'senate', role: 'Chair of the Majority Conference', name: 'Jose Serrano' },
    { chamber: 'senate', role: 'Majority Whip', name: 'Leroy Comrie' },
    { chamber: 'senate', role: 'Majority Deputy Whip', name: 'Joseph Addabbo' },
    { chamber: 'senate', role: 'Minority Leader', name: 'Robert G. Ortt' },
    { chamber: 'senate', role: 'Deputy Minority Leader and Floor Leader', name: 'Andrew Lanza' },
    { chamber: 'senate', role: 'Chair of the Senate Minority Conference', name: 'Pamela Helming' },
    { chamber: 'senate', role: 'Minority Whip', name: 'Patrick M. Gallivan' },
    { chamber: 'senate', role: 'Assistant Minority Leader', name: 'Joseph A. Griffo' },
    { chamber: 'assembly', role: 'Speaker', name: 'Carl E. Heastie' },
    { chamber: 'assembly', role: 'Majority Leader', name: 'Crystal D. Peoples-Stokes' },
    { chamber: 'assembly', role: 'Speaker Pro Tempore', name: 'Pamela J. Hunter' },
    { chamber: 'assembly', role: 'Deputy Speaker', name: 'Phil Ramos' },
    { chamber: 'assembly', role: 'Deputy Majority Leader', name: 'Charles D. Fall' },
    { chamber: 'assembly', role: 'Majority Whip', name: 'Rodneyse Bichotte Hermelyn' },
    { chamber: 'assembly', role: 'Deputy Majority Whip', name: 'Stefani Zinerman' },
    { chamber: 'assembly', role: 'Minority Leader', name: 'Edward P. Ra' },
    { chamber: 'assembly', role: 'Minority Leader Pro Tempore', name: 'Mary Beth Walsh' },
    { chamber: 'assembly', role: 'Deputy Minority Leader', name: 'Ken Blankenbush' },
    { chamber: 'assembly', role: 'Minority Whip', name: 'David DiPietro' },
    { chamber: 'assembly', role: 'Deputy Minority Whip', name: 'Doug Smith' },
  ],
  // ohiosenate.gov/members + ohiohouse.gov/members (136th GA)
  OH: [
    { chamber: 'senate', role: 'President', name: 'Rob McColley' },
    { chamber: 'senate', role: 'President Pro Tempore', name: 'Bill Reineke' },
    { chamber: 'senate', role: 'Majority Floor Leader', name: 'Theresa Gavarone' },
    { chamber: 'senate', role: 'Majority Whip', name: 'George F. Lang' },
    { chamber: 'senate', role: 'Minority Leader', name: 'Nickie J. Antonio' },
    { chamber: 'senate', role: 'Assistant Minority Leader', name: 'Hearcel F. Craig' },
    { chamber: 'senate', role: 'Minority Whip', name: 'Kent Smith' },
    { chamber: 'senate', role: 'Assistant Minority Whip', name: 'Beth Liston' },
    { chamber: 'assembly', role: 'Speaker of the House', name: 'Matt Huffman' },
    { chamber: 'assembly', role: 'Speaker Pro Tempore', name: 'Gayle Manning' },
    { chamber: 'assembly', role: 'Assistant Speaker Pro Tempore', name: 'Phil Plummer' },
    { chamber: 'assembly', role: 'Majority Floor Leader', name: 'Marilyn John' },
    { chamber: 'assembly', role: 'Assistant Majority Floor Leader', name: 'Adam C. Bird' },
    { chamber: 'assembly', role: 'Majority Whip', name: 'Riordan T. McClain' },
    { chamber: 'assembly', role: 'Minority Leader', name: 'Dani Isaacsohn' },
    { chamber: 'assembly', role: 'Assistant Minority Leader', name: 'Phillip M. Robinson, Jr.' },
    { chamber: 'assembly', role: 'Minority Whip', name: 'Beryl Brown Piccolantonio' },
    { chamber: 'assembly', role: 'Assistant Minority Whip', name: 'Desiree Tims' },
  ],
  // senate.michigan.gov/senators/leadership + house.mi.gov/Leadership
  MI: [
    { chamber: 'senate', role: 'Majority Leader', name: 'Winnie Brinks' },
    { chamber: 'senate', role: 'Assistant Majority Leader', name: 'Darrin Camilleri' },
    { chamber: 'senate', role: 'President Pro Tempore', name: 'Jeremy Moss' },
    { chamber: 'senate', role: 'Assistant President Pro Tempore', name: 'Erika Geiss' },
    { chamber: 'senate', role: 'Assistant President Pro Tempore', name: 'John Cherry' },
    { chamber: 'senate', role: 'Majority Floor Leader', name: 'Sam Singh' },
    { chamber: 'senate', role: 'Assistant Majority Floor Leader', name: 'Jeff Irwin' },
    { chamber: 'senate', role: 'Majority Caucus Chairperson', name: 'Dayna Polehanki' },
    { chamber: 'senate', role: 'Majority Whip', name: 'Mallory McMorrow' },
    { chamber: 'senate', role: 'Assistant Majority Whip', name: 'Mary Cavanagh' },
    { chamber: 'senate', role: 'Minority Leader', name: 'Aric Nesbitt' },
    { chamber: 'senate', role: 'Assistant Minority Leader', name: 'Rick Outman' },
    { chamber: 'senate', role: 'Minority Floor Leader', name: 'Dan Lauwers' },
    { chamber: 'senate', role: 'Assistant Minority Floor Leader', name: 'Lana Theis' },
    { chamber: 'senate', role: 'Minority Caucus Chairperson', name: 'Kevin Daley' },
    { chamber: 'senate', role: 'Minority Whip', name: 'Roger Victory' },
    { chamber: 'senate', role: 'Assistant Minority Whip', name: 'Mark Huizenga' },
    { chamber: 'assembly', role: 'Speaker of the House', name: 'Matt Hall' },
    { chamber: 'assembly', role: 'Speaker Pro Tempore', name: 'Rachelle Smit' },
    { chamber: 'assembly', role: 'Majority Floor Leader', name: 'Bryan Posthumus' },
    { chamber: 'assembly', role: 'Democratic Leader', name: 'Ranjeev Puri' },
    { chamber: 'assembly', role: 'Democratic Floor Leader', name: 'John Fitzgerald' },
  ],
  // lrb.hawaii.gov (Senate) + capitol.hawaii.gov (House), 33rd Legislature
  HI: [
    { chamber: 'senate', role: 'President', name: 'Ronald D. Kouchi' },
    { chamber: 'senate', role: 'Vice President', name: 'Michelle N. Kidani' },
    { chamber: 'senate', role: 'Majority Leader', name: 'Dru Mamo Kanuha' },
    { chamber: 'senate', role: 'Majority Floor Leader', name: 'Glenn Wakai' },
    { chamber: 'senate', role: 'Assistant Majority Floor Leader', name: 'Lynn DeCoite' },
    { chamber: 'senate', role: 'Majority Policy Leader', name: 'Les Ihara, Jr.' },
    { chamber: 'senate', role: 'Majority Whip', name: 'Lorraine R. Inouye' },
    { chamber: 'senate', role: 'Assistant Majority Whip', name: 'Troy N. Hashimoto' },
    { chamber: 'senate', role: 'Assistant Majority Whip', name: 'Jarrett Keohokalole' },
    { chamber: 'senate', role: 'Assistant Majority Whip', name: 'Chris Lee' },
    { chamber: 'senate', role: 'Assistant Majority Whip', name: 'Herbert M. Richards III' },
    { chamber: 'senate', role: 'Minority Leader', name: 'Brenton Awa' },
    { chamber: 'senate', role: 'Minority Floor Leader', name: 'Samantha DeCorte' },
    { chamber: 'senate', role: 'Assistant Minority Floor Leader', name: 'Kurt Fevella' },
    { chamber: 'assembly', role: 'Speaker', name: 'Nadine K. Nakamura' },
    { chamber: 'assembly', role: 'Vice Speaker', name: 'Linda Ichiyama' },
    { chamber: 'assembly', role: 'Majority Leader', name: 'Sean Quinlan' },
    { chamber: 'assembly', role: 'Majority Caucus Leader', name: 'Kirstin Kahaloa' },
    { chamber: 'assembly', role: 'Majority Floor Leader', name: 'Dee Morikawa' },
    { chamber: 'assembly', role: 'Assistant Majority Floor Leader', name: 'Trish La Chica' },
    { chamber: 'assembly', role: 'Majority Whip', name: 'Lisa Kitagawa' },
    { chamber: 'assembly', role: 'Majority Whip', name: 'Tyson K. Miyake' },
    { chamber: 'assembly', role: 'Majority Whip', name: 'Amy A. Perruso' },
    { chamber: 'assembly', role: 'Minority Leader', name: 'Lauren Matsumoto' },
    { chamber: 'assembly', role: 'Minority Floor Leader', name: 'Diamond Garcia' },
    { chamber: 'assembly', role: 'Assistant Minority Leader', name: 'David Alcos III' },
    { chamber: 'assembly', role: 'Assistant Minority Floor Leader', name: 'Julie Reyes Oda' },
    { chamber: 'assembly', role: 'Minority Whip', name: 'Elijah Pierick' },
  ],
  // legis.iowa.gov/legislators/leadership (91st GA)
  IA: [
    { chamber: 'senate', role: 'President of the Senate', name: 'Amy Sinclair' },
    { chamber: 'senate', role: 'President Pro Tempore', name: 'Ken Rozenboom' },
    { chamber: 'senate', role: 'Majority Leader', name: 'Mike Klimesh' },
    { chamber: 'senate', role: 'Majority Whip', name: 'Dan Zumbach' },
    { chamber: 'senate', role: 'Democratic Leader', name: 'Janice Weiner' },
    { chamber: 'senate', role: 'Democratic Whip', name: 'Matt Blake' },
    { chamber: 'assembly', role: 'Speaker', name: 'Pat Grassley' },
    { chamber: 'assembly', role: 'Speaker Pro Tempore', name: 'John H. Wills' },
    { chamber: 'assembly', role: 'Majority Leader', name: 'Bobby Kaufmann' },
    { chamber: 'assembly', role: 'Majority Whip', name: 'Henry Stone' },
    { chamber: 'assembly', role: 'Minority Leader', name: 'Brian Meyer' },
    { chamber: 'assembly', role: 'Minority Whip', name: 'Sean Bagniewski' },
  ],
  // palegis.us senate-officers + house-officers
  PA: [
    { chamber: 'senate', role: 'President Pro Tempore', name: 'Kim Ward' },
    { chamber: 'senate', role: 'Majority Floor Leader', name: 'Joe Pittman' },
    { chamber: 'senate', role: 'Majority Whip', name: 'Wayne Langerholc' },
    { chamber: 'senate', role: 'Majority Caucus Chair', name: 'Kristin Phillips-Hill' },
    { chamber: 'senate', role: 'Majority Caucus Secretary', name: 'Camera Bartolotta' },
    { chamber: 'senate', role: 'Majority Caucus Administrator', name: 'Lisa Baker' },
    { chamber: 'senate', role: 'Majority Policy Committee Chair', name: 'David Argall' },
    { chamber: 'senate', role: 'Majority Appropriations Committee Chair', name: 'Scott Martin' },
    { chamber: 'senate', role: 'Minority Floor Leader', name: 'Jay Costa' },
    { chamber: 'senate', role: 'Minority Whip', name: 'Christine Tartaglione' },
    { chamber: 'senate', role: 'Minority Caucus Chair', name: 'Maria Collett' },
    { chamber: 'senate', role: 'Minority Caucus Secretary', name: 'Steven Santarsiero' },
    { chamber: 'senate', role: 'Minority Caucus Administrator', name: 'Judith Schwank' },
    { chamber: 'senate', role: 'Minority Policy Committee Chair', name: 'Nick Miller' },
    { chamber: 'senate', role: 'Minority Appropriations Committee Chair', name: 'Vincent Hughes' },
    { chamber: 'assembly', role: 'Speaker of the House', name: 'Joanna McClinton' },
    { chamber: 'assembly', role: 'Majority Leader', name: 'Matthew Bradford' },
    { chamber: 'assembly', role: 'Majority Whip', name: 'Michael Schlossberg' },
    { chamber: 'assembly', role: 'Majority Caucus Chair', name: 'Robert Matzie' },
    { chamber: 'assembly', role: 'Majority Caucus Secretary', name: 'Tina Davis' },
    { chamber: 'assembly', role: 'Majority Caucus Administrator', name: 'Leanne Krueger' },
    { chamber: 'assembly', role: 'Majority Policy Committee Chair', name: 'Ryan Bizzarro' },
    { chamber: 'assembly', role: 'Majority Appropriations Committee Chair', name: 'Jordan Harris' },
    { chamber: 'assembly', role: 'Republican Leader', name: 'Jesse Topper' },
    { chamber: 'assembly', role: 'Republican Whip', name: "Timothy J. O'Neal" },
    { chamber: 'assembly', role: 'Republican Caucus Chair', name: 'Martina White' },
    { chamber: 'assembly', role: 'Republican Caucus Secretary', name: 'Clint Owlett' },
    { chamber: 'assembly', role: 'Republican Caucus Administrator', name: 'Sheryl Delozier' },
    { chamber: 'assembly', role: 'Republican Policy Committee Chair', name: 'David Rowe' },
    { chamber: 'assembly', role: 'Republican Appropriations Committee Chair', name: 'James Struzzi' },
  ],
  // malegislature.gov/Legislators/Leadership (194th General Court)
  MA: [
    { chamber: 'senate', role: 'President', name: 'Karen E. Spilka' },
    { chamber: 'senate', role: 'President Pro Tempore', name: 'William N. Brownsberger' },
    { chamber: 'senate', role: 'Majority Leader', name: 'Cynthia Stone Creem' },
    { chamber: 'senate', role: 'Assistant Majority Leader', name: 'Joan B. Lovely' },
    { chamber: 'senate', role: 'Assistant Majority Leader', name: 'Michael J. Barrett' },
    { chamber: 'senate', role: 'Assistant Majority Leader', name: 'Sal N. DiDomenico' },
    { chamber: 'senate', role: 'Majority Whip', name: 'Michael F. Rush' },
    { chamber: 'senate', role: 'Assistant Majority Whip', name: 'Julian Cyr' },
    { chamber: 'senate', role: 'Minority Leader', name: 'Bruce E. Tarr' },
    { chamber: 'senate', role: 'Assistant Minority Leader', name: "Patrick M. O'Connor" },
    { chamber: 'senate', role: 'Assistant Minority Leader', name: 'Ryan C. Fattman' },
    { chamber: 'senate', role: 'Assistant Minority Leader', name: 'Peter J. Durant' },
    { chamber: 'senate', role: 'Assistant Minority Leader', name: 'Kelly A. Dooner' },
    { chamber: 'assembly', role: 'Speaker of the House', name: 'Ronald Mariano' },
    { chamber: 'assembly', role: 'Speaker Pro Tempore', name: 'Kate Hogan' },
    { chamber: 'assembly', role: 'Majority Leader', name: 'Mike Moran' }, // "Michael J. Moran" on the official page; roster lists "Mike Moran"
    { chamber: 'assembly', role: 'Assistant Majority Leader', name: 'Alice Hanlon Peisch' },
    { chamber: 'assembly', role: 'Second Assistant Majority Leader', name: 'Frank A. Moran' },
    { chamber: 'assembly', role: 'Second Assistant Majority Leader', name: 'Paul J. Donato' },
    { chamber: 'assembly', role: 'Minority Leader', name: 'Bradley H. Jones, Jr.' },
    { chamber: 'assembly', role: 'First Assistant Minority Leader', name: 'Kimberly N. Ferguson' },
    { chamber: 'assembly', role: 'Second Assistant Minority Leader', name: 'Paul K. Frost' },
    { chamber: 'assembly', role: 'Third Assistant Minority Leader', name: 'David K. Muradian, Jr.' },
    { chamber: 'assembly', role: 'Third Assistant Minority Leader', name: 'David T. Vieira' },
  ],
};
